name: Release Build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build'
        required: true
        default: 'dev'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Run tests
      run: make test
      
    - name: Run linter
      run: make lint
      
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: ['1.21']
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            platform: linux
            suffix: ''
          - os: macos-latest
            platform: darwin
            suffix: ''
          - os: windows-latest
            platform: windows
            suffix: '.exe'
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
        
    - name: Get dependencies
      run: go mod download
      
    - name: Get version
      id: version
      run: |
        if [[ ${{ github.event_name }} == 'workflow_dispatch' ]]; then
          echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
        else
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        fi
        
    - name: Build
      run: |
        OUTPUT_NAME="pecel"
        if [ "${{ matrix.platform }}" = "windows" ]; then
          OUTPUT_NAME="pecel.exe"
        fi
        GOOS=${{ matrix.platform }} GOARCH=amd64 \
          go build -ldflags="-s -w -X main.version=${{ env.VERSION }}" \
          -o "$OUTPUT_NAME" .
        mkdir -p dist/${{ matrix.platform }}-amd64
        mv "$OUTPUT_NAME" dist/${{ matrix.platform }}-amd64/
        
    - name: Build ARM64 (Linux/macOS)
      if: matrix.os != 'windows-latest'
      run: |
        OUTPUT_NAME="pecel"
        if [ "${{ matrix.platform }}" = "windows" ]; then
          OUTPUT_NAME="pecel.exe"
        fi
        GOOS=${{ matrix.platform }} GOARCH=arm64 \
          go build -ldflags="-s -w -X main.version=${{ env.VERSION }}" \
          -o "$OUTPUT_NAME-arm64" .
        mkdir -p dist/${{ matrix.platform }}-arm64
        mv "$OUTPUT_NAME-arm64" dist/${{ matrix.platform }}-arm64/
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-binaries
        path: dist/
        
  release:
    runs-on: ubuntu-latest
    needs: [test, build]
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: dist
        pattern: '*-binaries'
        merge-multiple: true
        
    - name: Generate checksums
      run: |
        cd dist
        find . -type f -name "pecel*" -exec sha256sum {} \; > checksums.txt
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/**/pecel*
          dist/checksums.txt
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
  docker:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Get version
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          bhangun/pecel:latest
          bhangun/pecel:${{ env.VERSION }}